initialization
pastel 
button := Color fromString: 'bae38a'.
borderButton := Color fromString: '2c5345'.
shape := Color fromString: 'f5e4a8'.
borderShape := Color fromString: 'f59f66'.
background := 'pharo-local/iceberg/guillermo-diaz/Tp-Final-POO/resources/banner.jpg'.
icon := 'pharo-local/iceberg/guillermo-diaz/Tp-Final-POO/resources/icon.png'.
table := Color gray. 
button2 := Color fromString: 'f0a422'.
panel := Color fromString: 'F5FF86'.
header := Color fromString: 'ffc198'.
headerLine := Color fromString: '57442e'.
icon := Color fromString: '674935'.
contrast := Color fromString: 'FDEEB2'

