initialization
pastel 
button := Color fromString: 'bae38a'.
borderButton := Color fromString: '2c5345'.
shape := Color fromString: 'f5e4a8'.
borderShape := Color fromString: 'f59f66'.
self iconPath; backgroundPath .
table := Color gray. 
button2 := Color fromString: 'f0a422'.
panel := Color fromString: 'F5FF86'.
header := Color fromString: 'ffc198'.
headerLine := Color fromString: '57442e'.
iconColor := Color fromString: '674935'.
contrast := Color fromString: 'FDEEB2'

