initialization
pastel 
button := Color fromString: 'bae38a'.
borderButton := Color fromString: '2c5345'.
shape := Color fromString: 'f5e4a8'.
borderShape := Color fromString: 'f59f66'.
"background := 'pharo-local/iceberg/Tp-Final-POO/resources/background4.jpg'."
background := 'pharo-local/iceberg/guillermo-diaz/Tp-Final-POO/resources/banner.jpg'.
table := Color gray. 
header := Color fromString: 'ffc198'.
headerLine := Color fromString: '57442e'.
icon := Color fromString: '674935'.
contrast := Color fromString: 'FDEEB2'

