as yet unclassified
colLibrosPrecargados 
| libros |
libros := OrderedCollection new.

libros add: (Libro crearLibroNombre: 'Cien años de soledad' editorial: 'Editorial Sudamericana' añoEdicion: 1967 autores: { (Autor crearAutorNombre: 'Gabriel García Márquez') }).
libros add: (Libro crearLibroNombre: '1984' editorial: 'Secker & Warburg' añoEdicion: 1949 autores: { (Autor crearAutorNombre: 'George Orwell') }).
libros add: (Audiolibro crearLibroNombre: 'Don Quijote de la Mancha' editorial: 'Francisco de Robles' añoEdicion: 1605 autores: { (Autor crearAutorNombre: 'Miguel de Cervantes') }).
libros add: (Audiolibro crearLibroNombre: 'Orgullo y prejuicio' editorial: 'T. Egerton, Whitehall' añoEdicion: 1813 autores: { (Autor crearAutorNombre: 'Jane Austen') }).
libros add: (Libro crearLibroNombre: 'Moby-Dick' editorial: 'Richard Bentley' añoEdicion: 1851 autores: { (Autor crearAutorNombre: 'Herman Melville') }).
libros add: (Libro crearLibroNombre: 'Ulises' editorial: 'Sylvia Beach' añoEdicion: 1922 autores: { (Autor crearAutorNombre: 'James Joyce') }).
libros add: (Libro crearLibroNombre: 'En busca del tiempo perdido' editorial: 'Grasset' añoEdicion: 1913 autores: { (Autor crearAutorNombre: 'Marcel Proust') }).
libros add: (Libro crearLibroNombre: 'Crimen y castigo' editorial: 'The Russian Messenger' añoEdicion: 1866 autores: { (Autor crearAutorNombre: 'Fiódor Dostoyevski') }).
libros add: (Libro crearLibroNombre: 'El Gran Gatsby' editorial: 'Charles Scribner''s Sons' añoEdicion: 1925 autores: { (Autor crearAutorNombre: 'F. Scott Fitzgerald') }).
libros add: (Audiolibro crearLibroNombre: 'Don Juan Tenorio' editorial: 'Desconocida' añoEdicion: 1844 autores: { (Autor crearAutorNombre: 'José Zorrilla') }).

libros add: (Libro crearLibroNombre: 'Mujercitas' editorial: 'Roberts Brothers' añoEdicion: 1868 autores: { (Autor crearAutorNombre: 'Louisa May Alcott') }).
libros add: (Libro crearLibroNombre: 'La Odisea' editorial: 'Desconocida' añoEdicion: -800 autores: { (Autor crearAutorNombre: 'Homero') }).
libros add: (Libro crearLibroNombre: 'Harry Potter y la piedra filosofal' editorial: 'Bloomsbury' añoEdicion: 1997 autores: { (Autor crearAutorNombre: 'J.K. Rowling') }).
libros add: (Audiolibro crearLibroNombre: 'El gran diseño' editorial: 'Bantam Press' añoEdicion: 2010 autores: { (Autor crearAutorNombre: 'Stephen Hawking'). (Autor crearAutorNombre: 'Leonard Mlodinow') }).
libros add: (Audiolibro crearLibroNombre: 'Cien sonetos de amor' editorial: 'Editorial Lord Cochrane' añoEdicion: 1959 autores: { (Autor crearAutorNombre: 'Pablo Neruda') }).
libros add: (Libro crearLibroNombre: 'Meditaciones' editorial: 'Desconocida' añoEdicion: 180 autores: { (Autor crearAutorNombre: 'Marco Aurelio') }).
libros add: (Libro crearLibroNombre: 'El amor en los tiempos del cólera' editorial: 'Oveja Negra' añoEdicion: 1985 autores: { (Autor crearAutorNombre: 'Gabriel García Márquez') }).
libros add: (Audiolibro crearLibroNombre: 'Los juegos del hambre' editorial: 'Scholastic Corporation' añoEdicion: 2008 autores: { (Autor crearAutorNombre: 'Suzanne Collins') }).
libros add: (Libro crearLibroNombre: 'La sombra del viento' editorial: 'Planeta' añoEdicion: 2001 autores: { (Autor crearAutorNombre: 'Carlos Ruiz Zafón') }).


libros add: (Libro crearLibroNombre: 'Jojos Bizarre Adventure: Phantom Blood' editorial: 'Shueisha' añoEdicion: 1987 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Libro crearLibroNombre: 'Jojos Bizarre Adventure: Battle Tendency' editorial: 'Shueisha' añoEdicion: 1987 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Libro crearLibroNombre: 'Jojo''s Bizarre Adventure: Stardust Crusaders' editorial: 'Shueisha' añoEdicion: 1989 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Libro crearLibroNombre: 'Jojo''s Bizarre Adventure: Diamond Is Unbreakable' editorial: 'Shueisha' añoEdicion: 1992 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Audiolibro crearLibroNombre: 'Jojo''s Bizarre Adventure: Vento Aureo' editorial: 'Shueisha' añoEdicion: 1995 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Libro crearLibroNombre: 'Jojo''s Bizarre Adventure: Stone Ocean' editorial: 'Shueisha' añoEdicion: 2000 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Libro crearLibroNombre: 'Jojo''s Bizarre Adventure: Steel Ball Run' editorial: 'Shueisha' añoEdicion: 2004 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Audiolibro crearLibroNombre: 'Jojolion' editorial: 'Shueisha' añoEdicion: 2011 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).
libros add: (Audiolibro crearLibroNombre: 'Jojolands' editorial: 'Shueisha' añoEdicion: 2021 autores: { (Autor crearAutorNombre: 'Hirohiko Araki') }).

libros add: (Audiolibro crearLibroNombre: 'One Piece: Romance Dawn' editorial: 'Shueisha' añoEdicion: 1997 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Orange Town' editorial: 'Shueisha' añoEdicion: 1997 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Syrup Village' editorial: 'Shueisha' añoEdicion: 1998 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Baratie' editorial: 'Shueisha' añoEdicion: 1998 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Audiolibro crearLibroNombre: 'One Piece: Arlong Park' editorial: 'Shueisha' añoEdicion: 1998 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Loguetown' editorial: 'Shueisha' añoEdicion: 1998 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Reverse Mountain' editorial: 'Shueisha' añoEdicion: 1999 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Audiolibro crearLibroNombre: 'One Piece: Whiskey Peak' editorial: 'Shueisha' añoEdicion: 1999 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Audiolibro crearLibroNombre: 'One Piece: Little Garden' editorial: 'Shueisha' añoEdicion: 1999 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Drum Island' editorial: 'Shueisha' añoEdicion: 2000 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Alabasta' editorial: 'Shueisha' añoEdicion: 2000 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Audiolibro crearLibroNombre: 'One Piece: Jaya' editorial: 'Shueisha' añoEdicion: 2001 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Audiolibro crearLibroNombre: 'One Piece: Skypiea' editorial: 'Shueisha' añoEdicion: 2002 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'One Piece: Water 7' editorial: 'Shueisha' añoEdicion: 2002 autores: { (Autor crearAutorNombre: 'Eiichiro Oda') }).
libros add: (Libro crearLibroNombre: 'Berserk' editorial: 'Hakusensha' añoEdicion: 2002 autores: { (Autor crearAutorNombre: 'Kentaro Miura') }).


^libros 